FINAL_COLUMN_ORDER = [
    "PATH",
    "PATH_WITHOUT_REVISION",
    "PART_NUMBER",
    "REVISION",
    "PRODUCT_NAME",
    "PRODUCTION_STATE",
    "INDENT_LEVEL",
    "UOM",
    "TRACKING",
    "IS_CONSUMABLE_STORABLE",
    "PARENT_BOM",
    "PARENT_REVISION",
    "TOP_LEVEL_BOM",
    "TOP_LEVEL_REVISION",
    "QUANTITY",
    "PROCUREMENT_INTENT",
    "ADJUSTED_QUANTITY",
    "total rolled up quantity",
    "ADJUSTED_PROCUREMENT_INTENT",
    "GLOBAL_ALTERNATE_PART_NUMBERS",
    "SUBSTITUTE_PART_NUMBERS",
    "Supply Plan and On-Hand Alternates",
    "Latest PO",
    "Latest Supplier",
    "Latest PO Creation Date",
    "Product",
    "Variant",
    "System",
    "Subsystem",
    "Gross Demand for BOM Line in past 8 weeks",
    "Net Total Demand for Part Number in past 8 weeks",
    "Current Week Realized Demand Consumption (each)",
    "Gross Demand for BOM Line in next 8 weeks",
    "Net Total Demand for Part Number in next 8 weeks",
    "Quantity Received, 8-Week Rolling Average (each)",
    "Quantity Received, Average Since Last Receipt (each)",
    "Current On-Hand Quantity (each)",
    "On Hand Delta to Current Week Demand (each)",
    "Current Quarantine Quantity (each)",
    "Current Week Realized Supply (each)",
    "Total Supply Plan, next 8 weeks (each)",
    "Average Supply Plan, next 8 weeks (each)",
    "Quantity Received, 8-Week Rolling Average (each) with alternates",
    "Quantity Received, Average Since Last Receipt (each) with alternates",
    "Current On-Hand Quantity (each) with alternates",
    "on hand product sets including alternates",
    "Current Quarantine Quantity (each) with alternates",
    "Current Week Realized Supply (each) with alternates",
    "Total Supply Plan, next 8 weeks (each) with alternates",
    "Average Supply Plan, next 8 weeks (each) with alternates",
    "On Hand Inventory Status",
    "Supply Plan Status",
    "Avg Shipments Status",
]
